# baseURL = 'https://silasvasconcelos.com'
baseURL = 'http://localhost:1313'
languageCode = 'pt-br'
title = 'Silas Vasconcelos'
theme = 'PaperMod'

sectionPagesMenu = 'main'

[params]
  socialIcons = [
    { name = "github", url = "https://github.com/silasvasconcelos" },
    { name = "linkedin", url = "https://linkedin.com/in/silasvasconcelos" }
  ]

  [params.homeInfoParams]
    Title = "Ol√° üëã"
    Content = """Sou **Desenvolvedor Full-stack** com mais de 14 anos de experi√™ncia, focado em entender as necessidades dos clientes e entregar solu√ß√µes eficientes e inovadoras.

Trabalho com diversas tecnologias como PHP, Python, C#, Node.js, al√©m de frameworks modernos como Laravel, Django, Vue.js e React. Tenho experi√™ncia em DevOps, arquitetura de eventos, servi√ßos de nuvem (AWS) e lideran√ßa t√©cnica.

Sou proativo e estou sempre buscando aprender novas tecnologias para criar solu√ß√µes inovadoras. Vamos conversar?"""